name: File Improtance Calculation

on: 
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  TruckFactor-Calculator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Maven
      uses: s4u/setup-maven-action@v1.2.1
      with:
        java-version: 11
        maven-version: 3.6.3
    
    - name: Build Maven
      working-directory: ./gittruckfactor 
      run: mvn package
